import type { ProjectConfig } from "./types";

// No top-level source/layer — this project uses deck.gl ArcLayer via DaveFlowsMap.
// Each sub-viz points to a separate GeoJSON file fetched at runtime.

export const daveFlowsProject: ProjectConfig = {
  id: "dave_flows",
  coordinates: [6.5, 46.55], // Vaud-Geneva region

  title: "DAVE Flows",
  description:
    "Origin-destination mobility flows modelled by the DAVE activity-based simulation for the Vaud-Geneva region (500m grid).",
  category: "Mobility",
  year: 2024,
  preview: "dave_flows_work.png",
  zoom: 9,
  pitch: 0,

  unit: "persons",
  info: "Source: DAVE simulation model, EPFL",

  renderer: "deckgl-arcs",

  subViz: [
    {
      id: "work",
      title: "Work Flows",
      description:
        "Each arc represents the simulated commuting displacement of workers at 10am across the Vaud-Geneva region. The flows are derived from the DAVE activity-based model, which assigns synthetic agents to residential and workplace locations on a 500m grid. Arc width encodes the number of persons travelling between each origin-destination pair, revealing the dominant commuting corridors and the polycentric structure of employment in the region.",
      renderer: "deckgl-arcs",
      dataUrl: "dave_flows_work.geojson",
    },
    {
      id: "outdoor",
      title: "Outdoor Flows",
      description:
        "This layer captures mobility flows generated by outdoor recreational and leisure activities taking place outside the home. Agents engaged in activities such as walking, cycling, or spending time in parks and open spaces contribute to these origin-destination patterns. The spatial distribution of outdoor flows reveals how green spaces and natural amenities attract movement from across the urban and peri-urban fabric of the Vaud-Geneva region.",
      renderer: "deckgl-arcs",
      dataUrl: "dave_flows_outdoor.geojson",
    },
    {
      id: "indoor_leisure",
      title: "Indoor Leisure Flows",
      description:
        "Indoor leisure flows represent trips to destinations such as shopping centres, cultural venues, restaurants, and sports facilities. These flows reflect discretionary travel patterns that are strongly shaped by the distribution of services and amenities across the region. Comparing indoor leisure flows with work flows highlights the contrasting spatial logics of obligatory and voluntary mobility, with leisure trips often exhibiting greater variety in destination and travel time.",
      renderer: "deckgl-arcs",
      dataUrl: "dave_flows_indoor_leisure.geojson",
    },
  ],
};
