import type { ProjectConfig } from "./types";

// No top-level source/layer — this project uses deck.gl ArcLayer via DaveFlowsMap.
// Each sub-viz points to a separate GeoJSON file fetched at runtime.

export const daveFlowsProject: ProjectConfig = {
  id: "dave_flows",
  coordinates: [6.5, 46.55], // Vaud-Geneva region

  title: "DAVE Flows",
  description: `
Origin-destination mobility flows from the _DAVE_ activity-based simulation across the Vaud-Geneva region, resolved on a 500 m grid. Synthetic agents are drawn from census, travel-survey, and land-use data, then routed through the day as they commute, shop, and move between leisure destinations. Each sub-view below isolates one slice of those daily trajectories.
`,
  category: "Mobility",
  year: 2024,
  preview: "dave_flows_work.png",
  zoom: 9,
  pitch: 0,

  unit: "persons",
  info: "Source: DAVE simulation model, EPFL",

  renderer: "deckgl-arcs",

  subViz: [
    {
      id: "work",
      title: "Work Flows",
      description:
        "Each arc traces a simulated commute at 10am across the Vaud-Geneva region. Synthetic agents are matched to residential and workplace tiles on the _DAVE_ 500 m grid; arc width maps to the number of persons on each origin-destination pair, bringing out the dominant commuting corridors and the polycentric structure of regional employment.",
      renderer: "deckgl-arcs",
      dataUrl: "dave_flows_work.geojson",
    },
    {
      id: "outdoor",
      title: "Outdoor Flows",
      description:
        "Trips generated by outdoor recreation: walking, cycling, parks, lakefronts, and other open spaces. The spatial pattern exposes how green and blue amenities pull movement out of the dense centre into peri-urban tiles, and flags the corridors where heat-mitigating vegetation is actually used rather than just mapped.",
      renderer: "deckgl-arcs",
      dataUrl: "dave_flows_outdoor.geojson",
    },
    {
      id: "indoor_leisure",
      title: "Indoor Leisure Flows",
      description:
        "Trips to shops, cultural venues, restaurants, and indoor sports facilities. These are discretionary journeys, shaped by how services cluster across the region. Compared side by side with the _Work_ layer, the spatial logics of obligatory and voluntary mobility look strikingly different, with leisure trips spread across more destinations and a wider band of travel times.",
      renderer: "deckgl-arcs",
      dataUrl: "dave_flows_indoor_leisure.geojson",
    },
  ],
};
