import maplibregl from "maplibre-gl";
import { Protocol, PMTiles } from "pmtiles";
import type { RequestParameters, GetResourceResponse } from "maplibre-gl";

// Singleton protocol shared across every component that mounts a maplibregl.Map.
// Keeping a single instance means the directory cache (header + root + leaf
// directories) is reused — switching from the globe to a project map doesn't
// re-fetch the same metadata.
export const pmtilesProtocol = new Protocol();

/**
 * Protocol handler to register with `maplibregl.addProtocol("pmtiles", …)`.
 *
 * The GHSL archive omits near-empty tiles (ocean — the build pipeline deletes
 * tiles < 500 B), for which `Protocol.tile` resolves `{data: null}`. MapLibre's
 * image request path settles neither success nor error on a null payload, so
 * those raster tiles would sit in state "loading" forever — blocking `idle` /
 * `areTilesLoaded()` whenever ocean is in view and disqualifying them as
 * zoom fallbacks. Substitute an empty buffer, which MapLibre turns into a
 * transparent loaded tile (the basemap's background shows through, matching
 * GHSL ocean). TileJSON requests pass through untouched.
 */
export async function pmtilesRequest(
  params: RequestParameters,
  abortController: AbortController,
): Promise<GetResourceResponse<unknown>> {
  const response = await pmtilesProtocol.tile(params, abortController);
  if (params.type !== "json" && response.data == null) {
    return { ...response, data: new Uint8Array() };
  }
  return response;
}

const GHSL_LIVE_URL = "https://urbes-viz.epfl.ch/geodata/ghsl.pmtiles";

// Zoom levels served from the bundled local pyramid in public/ghsl-low/
// (generated by scripts/extract-ghsl-low.mjs) instead of the remote archive.
const GHSL_LOW_MAX_ZOOM = 5;

/**
 * Handler for the "ghsl://{z}/{x}/{y}" protocol behind the ghsl-urban raster
 * source. One source, two backends: z0–5 come from the bundled local tiles
 * (same-origin, browser-cached — they paint within a few frames on first load
 * and are near-instant fallbacks when MapLibre requests coarse ancestors of a
 * still-loading deep tile), z6+ from the remote PMTiles archive. Keeping it a
 * single source means MapLibre swaps a coarse tile for the sharp one when it
 * arrives, instead of blending two raster layers — GHSL tiles have transparent
 * no-settlement pixels, so a stacked low-res layer would stay visible through
 * loaded high-res tiles forever.
 */
export async function ghslRequest(
  params: RequestParameters,
  abortController: AbortController,
): Promise<GetResourceResponse<unknown>> {
  const match = params.url.match(/^ghsl:\/\/(\d+)\/(\d+)\/(\d+)$/);
  if (!match) throw new Error(`Unexpected ghsl tile URL: ${params.url}`);
  const [, z, x, y] = match;

  if (Number(z) <= GHSL_LOW_MAX_ZOOM) {
    const response = await fetch(`/ghsl-low/${z}/${x}/${y}.webp`, {
      signal: abortController.signal,
    });
    // The local pyramid is complete (missing-ocean tiles ship as transparent
    // placeholders), so a miss here is exceptional — degrade to an empty
    // (transparent) tile rather than an errored one.
    if (!response.ok) return { data: new Uint8Array() };
    return { data: await response.arrayBuffer() };
  }

  return pmtilesRequest(
    { ...params, url: `pmtiles://${GHSL_LIVE_URL}/${z}/${x}/${y}` },
    abortController,
  );
}

let protocolsRegistered = false;

// Registers the shared "pmtiles" and "ghsl" protocols once, app-wide. Every
// component that mounts a maplibregl.Map calls this before constructing it.
export function registerProtocols(): void {
  if (protocolsRegistered) return;
  protocolsRegistered = true;
  maplibregl.addProtocol("pmtiles", pmtilesRequest);
  maplibregl.addProtocol("ghsl", ghslRequest);
}

// Kicks off the PMTiles header + root-directory range request before any map
// canvas mounts. Called from main.ts, so the fetch runs in parallel with
// Vue/Pinia/router/Quasar setup. By the time Globe3D mounts, the directory
// cache is warm and tile reads start immediately.
export function prefetchGhsl(): void {
  const live = new PMTiles(GHSL_LIVE_URL);
  pmtilesProtocol.add(live);
  void live.getHeader();
}
